FROM node:lts AS runtime

ARG PUBLIC_SANITY_PROJECT_ID=${PUBLIC_SANITY_PROJECT_ID}
ARG PUBLIC_SANITY_DATASET=${PUBLIC_SANITY_DATASET}
ARG PUBLIC_SANITY_API_VERSION=${PUBLIC_SANITY_API_VERSION}
ARG REVALIDATE_SECRET=${REVALIDATE_SECRET}
ARG CREATE_TOKEN=${CREATE_TOKEN}
ARG GMAIL_USER=${GMAIL_USER}
ARG GMAIL_PASSWORD=${GMAIL_PASSWORD}
ARG GLASSNO_EMAIL=${GLASSNO_EMAIL}
ARG PUBLIC_EMAIL_ENDPOINT=${PUBLIC_EMAIL_ENDPOINT}
ARG PUBLIC_GOOGLE_MAPS_KEY=${PUBLIC_GOOGLE_MAPS_KEY}
ARG CLIENT_ID=${CLIENT_ID}
ARG URL=${URL}
ARG CLIENT_SECRET=${CLIENT_SECRET}

RUN corepack enable
WORKDIR /app

COPY . .

RUN pnpm install --prod
RUN pnpm build

ENV PUBLIC_SANITY_PROJECT_ID=${PUBLIC_SANITY_PROJECT_ID}
ENV PUBLIC_SANITY_DATASET=${PUBLIC_SANITY_DATASET}
ENV PUBLIC_SANITY_API_VERSION=${PUBLIC_SANITY_API_VERSION}
ENV REVALIDATE_SECRET=${REVALIDATE_SECRET}
ENV CREATE_TOKEN=${CREATE_TOKEN}
ENV GMAIL_USER=${GMAIL_USER}
ENV GMAIL_PASSWORD=${GMAIL_PASSWORD}
ENV GLASSNO_EMAIL=${GLASSNO_EMAIL}
ENV PUBLIC_EMAIL_ENDPOINT=${PUBLIC_EMAIL_ENDPOINT}
ENV PUBLIC_GOOGLE_MAPS_KEY=${PUBLIC_GOOGLE_MAPS_KEY}
ENV PORT=${PORT}
ENV URL=${URL}
ENV CLIENT_ID=${CLIENT_ID}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV HOST=0.0.0.0
ENV PORT=8100
EXPOSE 8100
CMD node server.mjs